//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cliente
{
    public int id_cliente { get; set; }
    public string Nombre { get; set; }
}

public partial class Producto
{
    public int id_producto { get; set; }
    public string des_producto { get; set; }
    public double precio { get; set; }
}

public partial class Proveedor
{
    public int id_proveedor { get; set; }
    public string Nombre { get; set; }
    public string Telefono { get; set; }
    public string Empresa { get; set; }
}

public partial class UsuariosSesion
{
    public int id_usuario { get; set; }
    public string usuario { get; set; }
    public string password { get; set; }
    public int IsLogged { get; set; }
    public int tipo { get; set; }
}
