//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class examenCRUDEntities5 : DbContext
{
    public examenCRUDEntities5()
        : base("name=examenCRUDEntities5")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Cliente> Cliente { get; set; }
    public DbSet<Producto> Producto { get; set; }
    public DbSet<Proveedor> Proveedor { get; set; }
    public DbSet<UsuariosSesion> UsuariosSesion { get; set; }
}
